version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: gitlab
      PGDATA: /data
    volumes:
      - db_data:/data

volumes:
  db_data: {}