version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: gitlab
      PGDATA: /data
    volumes:
      - db_data:/data
  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    volumes:
      - "grafana:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    user: "104"
    ports:
      - "5433:3000"

volumes:
  db_data: {}
  grafana: {}
